site_name: snow-pc
site_description: A python package for automated processing of point clouds to simplify elevation creation, co-registration and differencing to facilitate the production of snow depth and vegetation products.
site_author: Surfix
site_url: https://Surfix.github.io/snow-pc
repo_url: https://github.com/Surfix/snow-pc

copyright: "Copyright &copy; 2023 - 2023 Naheem Adebisi"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb",
                            "docs/examples/notebooks/*",
          ]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    # - Usage: usage.md
    - Contributing: contributing.md
    # - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/Surfix/snow-pc/issues
    # - Examples:
    #     - examples/examples.ipynb
    - API Reference:
          - prepare module: prepare.md
          - filtering module: filtering.md
          - modeling module: modeling.md
          - align_pc module: align_pc.md
          - snow_pc module: snow_pc.md
